### ISSUE TITLE
TODO / 待办事项

### ISSUE THREAD

**Issue by Xiaokang2022** [Xiaokang2022/maliang#50]
> [!TIP]
> Entries for this to-do item have the following 3 statuses:  
> 此待办事项的条目有以下 3 种状态：
>
> * 🔥 In Development / 开发中
> * 📌 In Planning / 计划中
> * 💡 In Consideration / 考虑中
>
> Items in development will most likely be implemented in the next release, planned items will be implemented in subsequent releases, and those under consideration may be added to the plan but may also be abandoned!  
> 开发中的条目将大概率在下个版本中实现，计划中的将在后续版本中实现，考虑中的可能会被加入到计划中，但也可能被放弃！

## 🔥 In Development / 开发中

* [ ] https://github.com/Xiaokang2022/tkintertools/issues/25

## 📌 In Planning / 计划中

* [ ] https://github.com/Xiaokang2022/tkintertools/issues/11
* [ ] Add highly customizable windows  
增加可高度定制的窗口
* [ ] Add support for GIFs  
增加对动图的支持
* [ ] Add text box widget  
增加文本框小部件
* [ ] Add table widget  
增加表格小部件

## 💡 In Consideration / 考虑中

* [ ] Add simple support for Markdown  
增加对 Markdown 的简单支持
* [ ] Add support for OpenCV  
增加对 OpenCV 的支持
* [ ] Add support for OpenGL  
增加对 OpenGL 的支持
* [ ] Introduce third-party web frameworks to enable web browsing  
引入第三方 Web 框架，以实现网页的浏览
* [ ] Support application-level text language localization switching  
支持应用程序级别的文本语言本地化切换

**Comment by Xiaokang2022** [comment]
此 Issue 已不再考虑，后续新的功能直接通过新的 Issue 来提出，而不是用该 Issue 收集
